In [4]:
import pandas as pd
from collections import Counter
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("BPI2016_Clicks_Logged_In.csv", 
                  encoding_errors="ignore", 
                  on_bad_lines='skip', 
                  sep=";",
                  usecols=['CustomerID', 'AgeCategory', 'Gender', 'Office_U', 'Office_W',
                         'SessionID', 'IPID', 'TIMESTAMP', 'VHOST', 'URL_FILE', 'PAGE_NAME',
                         'REF_URL_category', 'page_load_error', 'page_action_detail', 'tip',
                         'service_detail', 'xps_info'
                        ],
                  dtype='unicode')

df["TIMESTAMP"] = pd.to_datetime(df["TIMESTAMP"], infer_datetime_format=True)

In [5]:
df = df.sort_values(by=["TIMESTAMP", "CustomerID", "SessionID"])
df.head(10)

,CustomerID,AgeCategory,Gender,Office_U,Office_W,SessionID,IPID,TIMESTAMP,VHOST,URL_FILE,PAGE_NAME,REF_URL_category,page_load_error,page_action_detail,tip,service_detail,xps_info
3271608,797444,50-65,M,238,238,10125891,99546,2015-07-01 02:36:59.713,digid.werk.nl,/werk_nl/werknemer/mijn_werkmap/postvak/mijn_b...,mijn_berichten,NaN,0,NaN,NaN,NaN,NaN
5687809,797444,50-65,M,238,238,10125891,99546,2015-07-01 02:37:13.210,digid.werk.nl,/werk_nl/werknemer/mijn_werkmap/werk-zoeken/mi...,mijn_cv,NaN,0,NaN,NaN,NaN,NaN
6113803,797444,50-65,M,238,238,10125891,99546,2015-07-01 02:37:21.187,digid.werk.nl,/werk_nl/werknemer/mijn_werkmap/werk-zoeken/mi...,mijn_cv,NaN,0,NaN,NaN,NaN,NaN
6167539,797444,50-65,M,238,238,10125891,99546,2015-07-01 02:38:42.573,digid.werk.nl,/werk_nl/werknemer/mijn_werkmap/doorgeven/mijn...,mijn_sollicitaties,NaN,0,NaN,NaN,NaN,NaN
6167542,797444,50-65,M,238,238,10125891,99546,2015-07-01 02:39:26.053,digid.werk.nl,/werk_nl/werknemer/mijn_werkmap/doorgeven/mijn...,mijn_sollicitaties,NaN,0,NaN,NaN,NaN,NaN
3812070,797444,50-65,M,238,238,10125891,99546,2015-07-01 02:41:04.587,digid.werk.nl,/werk_nl/werknemer/mijn_werkmap/doorgeven/taken,taken,NaN,0,NaN,NaN,NaN,NaN
4089803,797444,50-65,M,238,238,10125891,99546,2015-07-01 02:41:23.543,digid.werk.nl,/werk_nl/werknemer/mijn_werkmap/doorgeven/taken,taken,NaN,0,NaN,NaN,NaN,NaN
4474611,797444,50-65,M,238,238,10125891,99546,2015-07-01 02:46:24.087,digid.werk.nl,/werk_nl/werknemer/mijn_werkmap/doorgeven/taken,taken,NaN,0,NaN,NaN,NaN,NaN
4563705,797444,50-65,M,238,238,10125891,99546,2015-07-01 02:46:38.593,digid.werk.nl,/werk_nl/werknemer/mijn_werkmap/doorgeven/mijn...,mijn_sollicitaties,NaN,0,NaN,NaN,NaN,NaN
3811098,797444,50-65,M,238,238,10125891,99546,2015-07-01 02:50:12.647,digid.werk.nl,/werk_nl/werknemer/mijn_werkmap/doorgeven/taken,taken,NaN,0,NaN,NaN,NaN,NaN

Activities