In [1]:

import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import matplotlib.pyplot as plt
import numpy as np
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
# imprt tree
from sklearn import tree
# import metrics
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.preprocessing import OneHotEncoder

In [2]:
df_raw = pd.read_csv("./labeled_data/labeled_df_15.csv", encoding_errors="ignore", on_bad_lines='skip', sep=",", index_col=False,
                    usecols=['SessionID','Activity','anomaly'])
# change anomaly to int
df_raw['anomaly'] = df_raw['anomaly'].astype(int)
df_raw

         SessionID                                           Activity  anomaly
0               46    /werk_nl/werknemer/mijn_werkmap/doorgeven/taken        0
1               46  /werk_nl/werknemer/mijn_werkmap/doorgeven/mijn...        0
2               46  /werk_nl/werknemer/mijn_werkmap/postvak/mijn_d...        0
3               46  /werk_nl/werknemer/mijn_werkmap/postvak/mijn_b...        0
4               46  /werk_nl/werknemer/mijn_werkmap/postvak/mijn_b...        0
...            ...                                                ...      ...
7174929   55314751                         /werk_nl/werknemer/werkmap        0
7174930   55314751    /werk_nl/werknemer/mijn_werkmap/doorgeven/taken        0
7174931   55314751    /werk_nl/werknemer/mijn_werkmap/doorgeven/taken        0
7174932   55314751    /werk_nl/werknemer/mijn_werkmap/doorgeven/taken        0
7174933   55314751    /werk_nl/werknemer/mijn_werkmap/doorgeven/taken        0

[7174934 rows x 3 columns]

In [2]:
# LSTM for sequence classification in the IMDB dataset
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing import sequence
# fix random seed for reproducibility
tf.random.set_seed(7)
# load the dataset but only keep the top n words, zero the rest
top_words = 5000
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=top_words)
# truncate and pad input sequences
max_review_length = 500
X_train = sequence.pad_sequences(X_train, maxlen=max_review_length)
X_test = sequence.pad_sequences(X_test, maxlen=max_review_length)
# create the model
embedding_vecor_length = 32
model = Sequential()
model.add(Embedding(top_words, embedding_vecor_length, input_length=max_review_length))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())
model.fit(X_train, y_train, epochs=3, batch_size=64)
# Final evaluation of the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))