In [1]:
import pm4py
import pandas as pd
import csv

In [2]:
log = pm4py.read_xes('BPI_Challenge_2012.xes.gz')
pd_df = pm4py.convert_to_dataframe(log)

c:\Python310\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
parsing log, completed traces :: 100%|██████████| 13087/13087 [00:09<00:00, 1407.43it/s]

In [16]:
df = pd_df.sort_values(['time:timestamp'])
pd_df.head(50)

,org:resource,lifecycle:transition,concept:name,time:timestamp,case:REG_DATE,case:concept:name,case:AMOUNT_REQ
0,112,COMPLETE,A_SUBMITTED,2011-10-01 00:38:44.546000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
1,112,COMPLETE,A_PARTLYSUBMITTED,2011-10-01 00:38:44.880000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
2,112,COMPLETE,A_PREACCEPTED,2011-10-01 00:39:37.906000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
3,112,SCHEDULE,W_Completeren aanvraag,2011-10-01 00:39:38.875000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
4,NaN,START,W_Completeren aanvraag,2011-10-01 11:36:46.437000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
5,10862,COMPLETE,A_ACCEPTED,2011-10-01 11:42:43.308000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
6,10862,COMPLETE,O_SELECTED,2011-10-01 11:45:09.243000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
7,10862,COMPLETE,A_FINALIZED,2011-10-01 11:45:09.243000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
8,10862,COMPLETE,O_CREATED,2011-10-01 11:45:11.197000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
9,10862,COMPLETE,O_SENT,2011-10-01 11:45:11.380000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
10,NaN,SCHEDULE,W_Nabellen offertes,2011-10-01 11:45:11.554000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
11,NaN,COMPLETE,W_Completeren aanvraag,2011-10-01 11:45:13.917000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
12,NaN,START,W_Nabellen offertes,2011-10-01 12:15:41.290000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
13,NaN,COMPLETE,W_Nabellen offertes,2011-10-01 12:17:08.924000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
14,10913,START,W_Nabellen offertes,2011-10-08 16:26:57.720000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
15,10913,COMPLETE,W_Nabellen offertes,2011-10-08 16:32:00.886000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
16,11049,START,W_Nabellen offertes,2011-10-10 11:32:22.495000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
17,11049,COMPLETE,O_SENT_BACK,2011-10-10 11:33:03.668000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
18,11049,SCHEDULE,W_Valideren aanvraag,2011-10-10 11:33:04.560000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
19,11049,COMPLETE,W_Nabellen offertes,2011-10-10 11:33:05.791000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
20,10629,START,W_Valideren aanvraag,2011-10-13 10:05:26.925000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
21,10629,COMPLETE,A_REGISTERED,2011-10-13 10:37:29.226000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
22,10629,COMPLETE,A_APPROVED,2011-10-13 10:37:29.226000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
23,10629,COMPLETE,O_ACCEPTED,2011-10-13 10:37:29.226000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
24,10629,COMPLETE,A_ACTIVATED,2011-10-13 10:37:29.226000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
25,10629,COMPLETE,W_Valideren aanvraag,2011-10-13 10:37:37.026000+02:00,2011-10-01 00:38:44.546000+02:00,173688,20000
26,112,COMPLETE,A_SUBMITTED,2011-10-01 08:08:58.256000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
27,112,COMPLETE,A_PARTLYSUBMITTED,2011-10-01 08:09:02.195000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
28,112,COMPLETE,A_PREACCEPTED,2011-10-01 08:09:56.648000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
29,112,SCHEDULE,W_Completeren aanvraag,2011-10-01 08:09:59.578000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
30,NaN,START,W_Completeren aanvraag,2011-10-01 11:37:32.393000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
31,NaN,COMPLETE,W_Completeren aanvraag,2011-10-01 11:43:13.178000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
32,NaN,START,W_Completeren aanvraag,2011-10-01 14:27:57.775000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
33,10862,COMPLETE,A_ACCEPTED,2011-10-01 14:33:54.614000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
34,10862,COMPLETE,A_FINALIZED,2011-10-01 14:35:46.016000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
35,10862,COMPLETE,O_SELECTED,2011-10-01 14:35:46.016000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
36,10862,COMPLETE,O_CREATED,2011-10-01 14:35:47.488000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
37,10862,COMPLETE,O_SENT,2011-10-01 14:35:47.583000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
38,NaN,SCHEDULE,W_Nabellen offertes,2011-10-01 14:35:47.682000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
39,NaN,COMPLETE,W_Completeren aanvraag,2011-10-01 14:35:48.791000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
40,NaN,START,W_Nabellen offertes,2011-10-01 14:36:13.443000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
41,NaN,COMPLETE,W_Nabellen offertes,2011-10-01 14:36:25.794000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
42,NaN,START,W_Nabellen offertes,2011-10-03 16:54:43.257000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
43,11120,COMPLETE,O_SELECTED,2011-10-03 16:56:17.731000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
44,11120,COMPLETE,O_CANCELLED,2011-10-03 16:56:17.731000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
45,11120,COMPLETE,O_CREATED,2011-10-03 16:56:19.613000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
46,11120,COMPLETE,O_SENT,2011-10-03 16:56:19.645000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
47,NaN,SCHEDULE,W_Nabellen offertes,2011-10-03 16:56:19.941000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
48,NaN,COMPLETE,W_Nabellen offertes,2011-10-03 16:56:21.195000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000
49,NaN,START,W_Nabellen offertes,2011-10-03 16:56:34.792000+02:00,2011-10-01 08:08:58.256000+02:00,173691,5000